### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yodarunamok** [rohm1/Css2Xpath#1]
This is the cleanest CSS to Xpath tool that I've found on github. From what I've seen, I think I'd like to incorporate the code into a project of my own (with attribution, of course.) However, as there's no license here, I'm not sure if that's okay.

My project is presently licensed under The Artistic License v2, and I do not foresee that changing. My project is a lightweight MVC framework.

Thank you.

**Comment by rohm1** [comment]
Hi,
thank you for your interest. I must say I am a bit surprised, I would expect something like the one from [Symfony](https://github.com/symfony/css-selector) to more up to date and more robust, but I've never tested it or had a better look at it, so I'll take your word for it.
I've added a license, the _Unlicense License_, so you are free to do whatever you want with it. In case you want to add it to your project using composer I'd consider publishing it to packagist.

**Comment by yodarunamok** [comment]
Thank you. To clarify, for me clean code is also concise. The Symphony translation bit is definitely not that.

That said, I've done some more digging in the past few days, and found [another possibility](https://github.com/theseer/css2xpath).

I'm not 100% sure which I'll end up using at this point, but I really do appreciate your help with this.
